### ISSUE TITLE
Missing files or invalid fixture scripts?

### ISSUE THREAD

**Issue by gmlewis** [ipc-sim/rigid-ipc#27]
I tried some of the examples in the "fixtures" directory, and the simulator works great!  Nice work!

However, I discovered that there are some examples that don't run either because their mesh files don't exist in the repo or because of some other problem.

For example, this example is missing its meshes:
https://github.com/ipc-sim/rigid-ipc/blob/main/fixtures/3D/mechanisms/expanding-lock-box.json#L11-L57

This example says `[2021-09-30 19:57:28.039] [error] Invalid Json file`:
https://github.com/ipc-sim/rigid-ipc/blob/main/fixtures/2D/compactor.json

**Comment by zfergus** [comment]
Glad to hear it is working well for you. 

The lockbox model was one that we bought [here](https://www.makersmuse.com/expanding-lock-box) and used in our paper, but we do not have the rights to distribute it, unfortunately. I left the JSON fixture in the repo simply to provide the setup and parameters used in our paper. Maybe I will add a note about this in the README. 

As for the broken JSON files, that is most likely a find-replace that left a trailing comma at the end of an object. JSON is annoying about that. Thanks for pointing me to that file. I will fix it and try to check all the files can be read.

**Comment by zfergus** [comment]
Fixed

**Comment by gmlewis** [comment]
Thank you again!
