### ISSUE TITLE
Reading output sequence rotations

### ISSUE THREAD

**Issue by hbaktash** [ipc-sim/rigid-ipc#34]
Hi! I'm playing around with `fixtures/3D/examples/example.json`. After saving the simulation, the sequence of rotations I see do not seem to match the input (`[30, 135, 0]`). Here are the first few rotations, when the object is in free fall, which should probably match the input:

> step 0
      [ 2.12731571 -1.43103249 -0.88119592]
step 1
      [ 2.12731571 -1.43103249 -0.88119592]
step 2
      [ 2.12731571 -1.43103249 -0.88119592]
step 3
      [ 2.12731571 -1.43103249 -0.88119592]
step 4
      [ 2.12731571 -1.43103249 -0.88119592]

Although loading the saved simulation back into the UI shows the correct sequence. Is there an initial transformation being applied to objects? I can't find more information in the output JSON file.

**Comment by zfergus** [comment]
I think what is happening is two things:
1. Those values are in radians while your input is in degrees
2. The stored rotation is in the inertial frame rather than the global frame. This is we align the object's inertia frame with the xyz internally and then use the inverse of this rotation times your input rotation as the initial rotation dof. This is accounted for during the restart.

**Comment by hbaktash** [comment]
Thanks! 
It also seems like the input is in Euler format (degrees), and output in axis-angle format (radians)? 
There is also an R0 being applied [here](https://github.com/ipc-sim/rigid-ipc/blob/main/src/physics/rigid_body_problem.cpp#L243). 
I'm not certain, but it seems like `R_input.T * R_1` should give us the inertial frame rotation.
I just want to extract the inertial rotation once and use it for different instances of the same example (each instance just has a different rotation).

**Comment by zfergus** [comment]
Yes, you are corect about the Euler vs rotation vector. I believe so. You can also check the GLTF writer which should have the correct transformation to put it back in a standard reference frame.

**Comment by hbaktash** [comment]
Thank you! Was able to extract the inertial frame with the approach mentioned earlier.
