### ISSUE TITLE
Missing STL for Scene expanding-lock-box.json

### ISSUE THREAD

**Issue by antoinebou12** [ipc-sim/rigid-ipc#35]
![image](https://github.com/user-attachments/assets/eb7270c6-4387-4572-a561-eec9da5ff587)

**Comment by zfergus** [comment]
Please see https://github.com/ipc-sim/rigid-ipc/issues/27#issuecomment-931832271

**Comment by antoinebou12** [comment]
Yes just saw in meshes thank !
